emails: str = "onwukaugosylvia2@gmail.com  " +\
            "ewatomiq56@gmail.com  " +\
            "akinloluwa60@gmail.com  " +\
            "omosexy_adebimpe@yahoo.com  " +\
            "bluetechsecured@gmail.com  " +\
            "ibrahimbashiru20@gmail.com  " +\
            "mamavemt@gmail.com  " +\
            "ogame@gmail.com  " +\
            "remzyadetunjis@gmail.com  " +\
            "kikelomokosoko@gmail.com  " +\
            "abubakardankaduna0096@gmail.com  " +\
            "maxwellvinn@gmail.com  " +\
            "emmasonchidinma@gmail.com  " +\
            "nkemdirimstanley@gmail.com  " +\
            "samueldave52@gmail.com  " +\
            "kanyinsolamariam22@gmail.com  " +\
            "contact.uniquebelfamenterprise@gmail.com  " +\
            "okiyomi@yahoo.com  " +\
            "kamordeenadegboye@gmail.com  " +\
            "taiwoopatunji@gmail.com  " +\
            "debbylabkey@gmail.com  " +\
            "akusutheresa@gmail.com  " +\
            "awohharrison@gmail.com  " +\
            "owolomosheibrahim1@gmail.com  " +\
            "jeffreychigbo@gmail.com  " +\
            "njokuuzomaik@gmail.com  " +\
            "jelilazeez607@gmail.com  " +\
            "veraisy6@gmail.com  " +\
            "olatinnovation2020@gmail.com  " +\
            "yinkarian@gmail.com  " +\
            "up2efe@gmail.com  " +\
            "jjmathsguru@gmail.com  " +\
            "joshuaadekoya1930@gmail.com  " +\
            "godwingeofrey@gmail.com  " +\
            "eseoghenebless@gmail.com  " +\
            "jamilusanidakingari@gmail.com  " +\
            "olamideodeyinka0@gmail.com  " +\
            "modupeafolabi121@gmail.com  " +\
            "uchennagodswill10@yahoo.com  " +\
            "ebiniyitemidire@gmail.com  " +\
            "greatdoradavid@gmail.com  " +\
            "bilkeesuabdullahi123@gmail.com  " +\
            "happinessministore@gmail.com  " +\
            "ijaleeman15@gmail.com  " +\
            "biz42brother@gmail.com  " +\
            "unity4goodliving@yahoo.com  " +\
            "emmagab77@gmail.com  " +\
            "olufiyogan@gmail.com  " +\
            "nathythegreat@gmail.com  " +\
            "fryogbjsh@gail.com  " +\
            "ibkay30@gmail.com  " +\
            "teemahadeola123@gmail.com  " +\
            "fridayukeredi@gmail.com  " +\
            "seebomani3602@gmail.com  " +\
            "c.e.o.kampulse@gmail.com  " +\
            "shelland291@gmail.com  " +\
            "ceeflozy1980@gmail.com  " +\
            "favourdivine373@gmail.com  " +\
            "olagabriel32@yahoo.com  " +\
            "donsimonmg@gmail.com  " +\
            "dtolojo85@gmail.com  " +\
            "kyleolora@gmail.com  " +\
            "atumininu646@gmail.com  " +\
            "ibodjemonday85@gmail.com  " +\
            "polycapeboh2@gmail.com  " +\
            "ishikyav@yahoo.com  " +\
            "olarenwajufavour764@gmail.com  " +\
            "saifullahiumarfaruk@gmail.com  " +\
            "abuhariamina24@gmail.com  " +\
            "otusmarine1@gmail.com  " +\
            "ofiemovictory22@gmail.com  " +\
            "aduramigbai1993@gmail.com  " +\
            "bayel.xandra@yahoo.com  " +\
            "emmanuellachimaechi@gmail.com  " +\
            "tegivy@gmail.com  " +\
            "ibrahimabbass1144@gmail.com  " +\
            "abigailayodele35@gmail.com  " +\
            "princessdammy994@gmail.com  " +\
            "ebadoufuoma23@gmail.com  " +\
            "onuohacharleschinedu@gmail.com  " +\
            "atoripat@gmail.com  " +\
            "desmondofega60@gmail.com  " +\
            "sunnyofie5@gmail.com  " +\
            "yakaezekiel48@gmail.com  " +\
            "benjaminbliss14@gmail.com  " +\
            "igeremoses@gmail.com  " +\
            "adinphery@gmail.com  " +\
            "marrisstella422@gmail.com  " +\
            "tayob106@gmail.com  " +\
            "mamuzopeace442@gmail.com  " +\
            "uzoma291@gmail.com  " +\
            "chiekezicross@gmail.com  " +\
            "ekezieiheanyi@gmail.com  " +\
            "aishatukb@gmail.com  " +\
            "iorumuyiwa@gmail.com  " +\
            "ukadikethankgod@gmail.com  " +\
            "mamaaakogba@gmail.com  " +\
            "ashemoroghaleblessing@gmail.com  " +\
            "agibabylizo@yahoo.com  " +\
            "afokeonome249@gmail.com  " +\
            "iorkyasecyril@gmail.com  " +\
            "jimohkabiratt@gmail.com  " +\
            "folakeekundayo18@gmail.com  " +\
            "ifepamilerin05@gmail.com  " +\
            "awofe2016@gmail.com  " +\
            "okwufaith24@gmail.com  " +\
            "piusebiemi@gmail.com  " +\
            "confyonyedikachi@gmail.com  " +\
            "keptedge@gmail.com  " +\
            "orindufestus@gmail.com  " +\
            "sannifatimat88@gmail.com  " +\
            "christopherc@gmail.com  " +\
            "victoreferuri@gmail.com  " +\
            "omasokeh1@gmail.com  " +\
            "ifeomaobiayon@gmail.com  " +\
            "johnfelicia148@gmail.com  " +\
            "ajuwonomolola4christ@gmail.com  " +\
            "oghenebrorhieimo@gmail.com  " +\
            "xristophernwogu@icloud.com  " +\
            "olumay0188@gmail.com  " +\
            "iyabooy3@gmail.com  " +\
            "mirian22@gmail.com  " +\
            "olapobamidele@gmail.com  " +\
            "solo2young@yahoo.com  " +\
            "Ofekeemillian22@gmail.com  " +\
            "gbadeboboseaderiike@gmail.com  " +\
            "blessingnancy929@gmail.com  " +\
            "johnkamsy22@gmail.com  " +\
            "omileyet321@gmail.com  " +\
            "johnblessingdamilola1@gmail.com  " +\
            "tosinakposibruke@gmail.com  " +\
            "adewale.omoboriowo@gmail.com  " +\
            "smartgardensuite@gmail.com  " +\
            "nelizu@live.com  " +\
            "st.paularemu@gmail.com  " +\
            "esirie897@gmail.com  " +\
            "samroy708@yahoo.com  " +\
            "udikezzylouis@gmail.com  " +\
            "folakeidowu13@gmail.com  " +\
            "dontechglobalintercom@yahoo.com  " +\
            "rumemofi2018@gmail.com  " +\
            "dblesstega@gmail.com  " +\
            "aanafada@yahoo.com  " +\
            "eanidobe@gmail.com  " +\
            "koboh93@gmail.com  " +\
            "omowunmiadebayo85@gmail.com  " +\
            "david.monedo@gmail.com  " +\
            "favour.chika2@gmail.com  " +\
            "sarahbrisibe@gmail.com  " +\
            "bisiade@gmail.com  " +\
            "jenevicaowofeweria@gmail.com  " +\
            "princesschibest73@gmail.com  " +\
            "pearlobodoako@gmail.com  " +\
            "fatimajane44@gmail.com  " +\
            "christianaobiajuru35@gmail.com  " +\
            "ashikasedoomercy@gmail.com  " +\
            "busariwariths@gmail.com  " +\
            "emuonoriode4life@gmail.com  " +\
            "Tanimulafia@gmail.com  " +\
            "joshuaogheneovo0@gmail.com  " +\
            "aresdam2017@gmail.com  " +\
            "ronkeangel@gmail.com  " +\
            "ewurejejohnson@gmail.com  " +\
            "abdulrafiuabdullateef59@gmail.com  " +\
            "ahmedfalodunahmed@gmail.com  " +\
            "omaibimadu@gmail.com  " +\
            "vwairhegift569@gmail.com  " +\
            "mustaphaaminubinji@gmail.com  " +\
            "queenerehab@gmail.com  " +\
            "blexzungucci994@gmail.com  " +\
            "emmanuelflorence92@gmail.com  " +\
            "zoeiriruaga@gmail.com  " +\
            "idrisualiyusanda@gmail.com  " +\
            "jamesokay47@gmail.com  " +\
            "saalujack@gmail.com  " +\
            "princesssalvation@gmail.com  " +\
            "chinonyeprisca49@gmail.com  " +\
            "ujohlight608@gmail.com  " +\
            "olaniyandeborah127@gmail.com  " +\
            "s82333392@gmail.com  " +\
            "kayodeeniayewu@gmail.com  " +\
            "juliusauzikpang@gmail.com  " +\
            "ijeomachris96@gmail.com  " +\
            "027@gmail.com  " +\
            "joshworld181@gmail.com  " +\
            "elijahkpam@gmail.com  " +\
            "aliyuaudi3200@gmail.com  " +\
            "harisubakoubale@gmail.com  " +\
            "abubakarmukhtar899@gmail.com  " +\
            "nkenchiss@gmail.com  " +\
            "comoyibo@gmail.com  " +\
            "omorezito@gmail.com  " +\
            "caramor4199@gmail.com  " +\
            "loveojem@gmail.com  " +\
            "aliisiyakaali@gmail.com  " +\
            "ogbudavid261@gmail.com  " +\
            "sanidantala30@gmail.com  " +\
            "samoluwabusolafolabi@gmail.com  " +\
            "melodyidogho@gmail.com  " +\
            "mostellight@gmail.com  " +\
            "dolsolfconsulting@gmail.com  " +\
            "atesebimaria@gmail.com  " +\
            "peaceobianuju321@gmail.com  " +\
            "ofonimegodwin@hotmail.com  " +\
            "gwanobefuseh@gmail.com  " +\
            "samuelenghaa@gmail.com  " +\
            "nicholasobinna589@gmail.com  " +\
            "gononoke@gmail.com  " +\
            "sodiqt040@gmail.com  " +\
            "ngosussy@gmail.com  " +\
            "dincredibleboy@gmail.com  " +\
            "danieljustind1@gmail.com  " +\
            "maltne142@gmail.com  " +\
            "lawrenciayahaya@gmail.com  " +\
            "taiwooki32@gmail.com  " +\
            "nwaokobiamaureen@gmail.com  " +\
            "adenikebamidele111@gmail.com  " +\
            "oluchimary600@gmail.com  " +\
            "malancy67@gmail.com  " +\
            "abdulwaheed.ismaila@yahoo.com  " +\
            "vincentmike594@gmail.com  " +\
            "meyiwatoritseju@gmail.com  " +\
            "Edwards_bottle@yahoo.com  " +\
            "mercyefiya@gmail.com  " +\
            "obioraossaiukagod@gmail.com  " +\
            "obohreine@gmail.com  " +\
            "onomeumubi1@gmail.com  " +\
            "mubaplaza@gmail.com  " +\
            "sirholyboysirholyboy@gmail.com  " +\
            "bamideleanuoluwapo2020@gmail.com  " +\
            "stephenlaban77@gmail.com  " +\
            "tomotighoejiro@gmail.com  " +\
            "omobuwa4real@yahoo.com  " +\
            "umarsidi.usa@gmail.com  " +\
            "chrisemmanuel7327@gmail.com  " +\
            "mathiasakange25@gmail.com  " +\
            "piusokoro0147@gmail.com  " +\
            "christianakuma5@gmail.com  " +\
            "opeoluwaolorunsogo@gmail.com  " +\
            "nnamsonjeff@gmail.com  " +\
            "aamanacommunication@gmail.com  " +\
            "OGHENERORHAPPY@GMAIL.COM  " +\
            "akinjacob12@gmail.com  " +\
            "rebeccamanarayaum@gmail.com  " +\
            "mahmudibrahimsidi@gmail.com  " +\
            "SIMONJULIET33@GMAIL.COM  " +\
            "Tolutec84@gmail.com  " +\
            "Zaraujakadda@gmail.com  " +\
            "endurance@gmail.com  " +\
            "Oluwatoyinobafemi4@gmail.com  " +\
            "chidiebubesamuel12@gmail.com  " +\
            "wicsongreat2009@yahoo.com  " +\
            "munirazare@gmail.com  " +\
            "doctortmartins0@gmail.com  " +\
            "Ebyboy@gmail.com  " +\
            "ibrahimausman009@gmail.com  " +\
            "debyp97@gmail.com  " +\
            "chukwuemekag6@gmail.com  " +\
            "mohammedsaid8717@gmail.com  " +\
            "alsen42018@gmail.com  " +\
            "charitymosy@gmail.com  " +\
            "lizzyberrye@gmail.com  " +\
            "soulskehike@gmail.com  " +\
            "affangaagnes@gmail.com  " +\
            "abdulmalikbabakalli636@gmail.com  " +\
            "chiedunzeakor@gmail.com  " +\
            "aganbionome@gmail.com  " +\
            "godfreyodere@gmail.com  " +\
            "emmanuelaguneto15@gmail.com  " +\
            "analuorac@gmail.com  " +\
            "crugbere002@gmail.com  " +\
            "alhussain3737@gmail.com  " +\
            "vinthyls@gmail.com  " +\
            "naseemnasaar35@gmail.com  " +\
            "omotoyosi2003@gmail.com  " +\
            "ibrahimbashar205@gmail.com  " +\
            "abubakarmuhammed.1122@gmail.com  " +\
            "gremamusa11@gmail.com  " +\
            "engine012@yahoo.com  " +\
            "abdulazizmm86@gmail.com  " +\
            "jbabasaleh@gmail.com  " +\
            "juliaughweri143@gmail.com  " +\
            "umar85530@gmail.com  " +\
            "shidonglobalconcept@gmail.com  " +\
            "mohammad.yakubusabo@gmail.com  " +\
            "olubiyimoyo@gmail.com  " +\
            "brightjoe001@gmail.com  " +\
            "habubakarumar21@gmail.com  " +\
            "sitoruparadise@gmail.com  " +\
            "mubeenyahaya@gmail.com  " +\
            "blessingnnenna12@gmail.com  " +\
            "skylink448@gmail.com  " +\
            "blessingojebewa@gmail.com  " +\
            "feteb4real@gmail.com  " +\
            "udosamuel938@gmail.com  " +\
            "adebisibolaji399@gmail.com  " +\
            "bamideleanuoluwapo2020@gmail.com  " +\
            "bukolaasifat2016@gmail.com  " +\
            "babanuma@yahoo.com  " +\
            "Tegaosiobetppb@gmail.com  " +\
            "nwankwokingsley2013@gmail.com  " +\
            "okonkwoifeanyi1991@gmail.com  " +\
            "ijekingsley@gmail.com  " +\
            "usmanalhajimala1971@gmail.com  " +\
            "davidfeelaz@gmail.com  " +\
            "s_okike@yahoo.com  " +\
            "adebayosegunraphael@gmail.com  " +\
            "mbrschisom@gmail.com  " +\
            "samuelajadi123@gmail.com  " +\
            "godwinbob69@gmail.com  " +\
            "onyinyeisodje00@gmail.com  " +\
            "aminumomo@yahoo.com  " +\
            "ossaimichael6@gmail.com  " +\
            "ugoben2013@gmail.com  " +\
            "calitex2003@gmail.com  " +\
            "belloahmad2054@gmail.com  " +\
            "wisdomjed23@gmail.com  " +\
            "stephenuzochukwuonyema@gmail.com  " +\
            "lawanharuna97@gmail.com  " +\
            "muazuadamujumbam131@gmail.com  " +\
            "kumaghabetter@gmail.com  " +\
            "agarastimijoy25@gmail.com  " +\
            "marojustin21@gmail.com  " +\
            "simeonshishi@gmail.com  " +\
            "bukolaadebayo11@gmail.com  " +\
            "Odikaesiemechristiana@gmail.com  " +\
            "udomaiboro@gmail.com  " +\
            "praisegodtariere@gmail.com  " +\
            "lovethuyuoyou2016@gmail.com  " +\
            "kuduanna1@gmail.com  " +\
            "fridayokatho@gmail.com  " +\
            "smartgarden202@yahoo.com  " +\
            "tegaaderoh@yahoo.com  " +\
            "Augustinagamage@yahoo.com  " +\
            "OnyiOnyedikachi78@gmail.com  " +\
            "sanusiseyo@gmail.com  " +\
            "emmandefo0@gmail.com  " +\
            "bilhasamuel298@gmail.com  " +\
            "kailausmangmw@gmail.com  " +\
            "ikennaolaedo25@gmail.com  " +\
            "augustajoan@gmail.com  " +\
            "abbahsani80@gmail.com  " +\
            "abrahamwominizibe@gmail.com  " +\
            "ayobamiayobola2@gmail.com  " +\
            "motunrayo227@yahoo.com  " +\
            "harryewhero@gmail.com  " +\
            "mbcsycltd@gmail.com  " +\
            "alimohammed3883@gmail.com  " +\
            "abubakargrema6110@gmail.com  " +\
            "cheteantonia@gmail.com  " +\
            "oweiagbe.ekioemi@gmail.com  " +\
            "ezeoyec@yahoo.com  " +\
            "leonyeabor@gmail.com  " +\
            "Babangidaharuna02@gmail.com  " +\
            "adamumuhammad5468@gmil.com  " +\
            "doctortmartins@yahoo.com  " +\
            "julietakpasa@gmail.com  " +\
            "justicekevin1@gmail.com  " +\
            "emmanuelblizelawrence@gmail.com  " +\
            "koredekobi@gmail.com  " +\
            "Careyjohnson@gmail.com  " +\
            "blessingeddy89@gmail.com  " +\
            "mercysunday164@gmail.com  " +\
            "edevel2000@gmail.com  " +\
            "abduharunamirnga@gmail.com  " +\
            "uthmanolawale74@gmail.com  " +\
            "lawanbadamasimiringab@gmail.com  " +\
            "ohwotakeochuko@gmail.com  " +\
            "jpower442@gmail.com  " +\
            "wilfko2@gmail.com  " +\
            "kalupatrick51@gmail.com  " +\
            "gladysmicheal2019@gmail.com  " +\
            "ojakovoprecious41@gmail.com  " +\
            "blessingolise2021@gmail.com  " +\
            "chinwechiekezi@gmail.com  " +\
            "esemuede.augustine1@gmail.com  " +\
            "nkechinedeye2016@gmail.com  " +\
            "chuklee2004@yahoo.com  " +\
            "scottemuakporedith@gmail.com  " +\
            "tasiuhussaini30@gmail.com  " +\
            "itayanesther@gmail.com  " +\
            "avac93315@gmail.com  " +\
            "Anthonyavura@gmail.com  " +\
            "chinechenkwokwu@gmail.com  " +\
            "jensamuel092@gmail.com  " +\
            "cornel042@yahoo.com  " +\
            "ambroseokoli@gmail.com  " +\
            "prettyjenny4truereality@yahoo.com  " +\
            "illustriousfemales@gmail.com  " +\
            "ariebimotimi@gmail.com  " +\
            "james67@yahoo.com  " +\
            "muomuobaby@yahoo.com  " +\
            "collinsobechi@gmail.com  " +\
            "rosemaryani2000@gmail.com  " +\
            "favourmeg22@gmail.com  " +\
            "info.mediatech@yahoo.com  " +\
            "preciouzglo@gmail.com  " +\
            "pepper080232@gmail.com  " +\
            "luckyelectelect@gmail.com  " +\
            "benima@gmail.com  " +\
            "feliciaadigun@gmail.com  " +\
            "inyang746@gmail.com  " +\
            "benjaminblessing609@gmail.com  " +\
            "manofgrace1982@gmail.com  " +\
            "ahuratimothy@gmail.com  " +\
            "justina.o@gmail.com  " +\
            "razibabajiya@gmail.com  " +\
            "ovieegedegbe021@gmail.com  " +\
            "ukamakaokafor@gmail.com  " +\
            "ibrahimkokary@gmail.com  " +\
            "tunjitogunloju@gmail.com  " +\
            "giftogbes@gmail.com  " +\
            "edetuwen@gmail.com  " +\
            "dimjogstech2@gmail.com  " +\
            "adefilaolamilekan6@gmail.com  " +\
            "gclara736@gmail.com  " +\
            "eletosegun@gmail.com  " +\
            "basilaaliu1@gmail.com  " +\
            "mariamtdavid@gmail.com  " +\
            "princedarlingtonpotential@gmail.com  " +\
            "matthewedwin44@gmail.com  " +\
            "osadjeregloria@gmail.com  " +\
            "binatuspeter@gmail.com  " +\
            "edafeomoro@gmail.com  " +\
            "benerdowoicho@gmail.com  " +\
            "nazifiisa01@gmail.com  " +\
            "kemeladeiagbeotu318@gmail.com  " +\
            "mansursaidu240@gmail.com  " +\
            "amabebequeen36@gmail.com  " +\
            "stellae482@gmail.com  " +\
            "emmyt29@gmail.com  " +\
            "sabbalidee707@gmail.com  " +\
            "elizabeth199035@yahoo.com  " +\
            "debbyedet07@gmail.com  " +\
            "Myetunde58@gmail.com  " +\
            "samuelstephanie1996@gmail.com  " +\
            "emumena231@gmail.com  " +\
            "ayaoweielson15@gmail.com  " +\
            "lugardabili1@gmail.com  " +\
            "humphreytex@gmail.com  " +\
            "efereboyaimbo@gmail.com  " +\
            "ifyoluchi355@gmail.com  " +\
            "moritzwilliams@gmail.com  " +\
            "ajiyababaganalawan16@gmail.com  " +\
            "nwaejinaka@gmail.com  " +\
            "onuchecynthia10@gmail.com  " +\
            "iamsmartplug@gmail.com  " +\
            "Annisamuel.AS@gmail.com  " +\
            "fuwokis2020@gmail.com  " +\
            "theresaogali@gmail.com  " +\
            "nkwochahenry8@gmail.com  " +\
            "stellaoluwemimo@gmail.com  " +\
            "liannabagwo@gmail.com  " +\
            "ajakpovifavour@gmail.com  " +\
            "osahen7535@gmail.com  " +\
            "odunzeleo@yahoo.com  " +\
            "mikeherlo34@gmail.com  " +\
            "isaaclukajrn@gmail.com  " +\
            "softqueen78@gmail.com  " +\
            "marisomoraka@gmail.com  " +\
            "josephosemeke30@gmail.com  " +\
            "aigbokietosan@gmail.com  " +\
            "ohiovera@gmail.com  " +\
            "fidechi@gmail.com  " +\
            "bigsam@gmail.com  " +\
            "peterloveth@gmail.com  " +\
            "ofurhiet@gmail.com  " +\
            "oshinsmitho1@gmail.com  " +\
            "adefunkekaffyibrahim@gmail.com  " +\
            "anuehondor@yahoo.com  " +\
            "omatseyeodons@gmail.com  " +\
            "ugonnaphilip2@gmail.com  " +\
            "nofad86@gmail.com  " +\
            "angelaumuks@gmail.com  " +\
            "samohj95@gmail.com  " +\
            "Abegosamsono@gmail.com  " +\
            "maymaxzy@gmail.com  " +\
            "imamibrahimidris495@gmail.com  " +\
            "abiolaracheal45@gmail.com  " +\
            "sahaji113@gmail.com  " +\
            "afolagbadebreakthrough@gmail.com  " +\
            "ghandiblessing0@gmail.com  " +\
            "oladimeji203@gmail.com  " +\
            "sekinatanita@gmail.com  " +\
            "joywada96@gmail.com  " +\
            "comfortbamishle@gmail.com  " +\
            "damilolaadeoye545@gmail.com "+\
            "tochukwuokoye16@gmail.com  " +\
            "charityjustus24@gmail.com  " +\
            "idrissani380@gmail.com  " +\
            "omolawunmi17@gmail.com  " +\
            "samailaibrahim133@gmail.com  " +\
            "odedede26@gmail.com  "


newEmails = "layefaabel@gmail.com, , kacymark20@gmail.com, , angelaebitebe54321@gmail.com, , kencarswaps1@gmail.com, , giftbamaiyi@gmail.com, , wumsol1@gmail.com, , olaogunomolara2017@gmail.com, , btenumah@yahoo.com, , akinfayemoromoke10@gmail.com, , esteephe29@gmail.com, , abiodunanuoluwapo45@gmail.com, , alatiseyetunde8@gmail.com, , onalamitoyin@gmail.com.com, , toppylee2009@yahoo.com, , adetinu560@gmail.com, , bolatitob32@gmail.com, , amejuotone@gmail.com, , spicykreemy@gmail.com, , shaibmercy196@gmail.com, , williams.pery@yahoo.com, , adedoyinmargaret3@gmail.com, , oluatosinseunfolorunso@gmail.com, , oyiboelvis0@gmail.com, , iegobaghapeace@gmail.com, , lorent4u12@gmail.com, , khessyjoseph18@gmail.com, , okesco2010@gmail.com, , stellamamu123@gmail.com, , salauabdulm@gmail.com, , deborahdeyenfa@gmail.com, , evwiesjenny@gmail.com, , thinkoteks@gmail.com, , ofurhiedove@gmail.com, , ogheneruonaevelyn55@gmail.com, , assalamcomputer.ng@gmail.com, , goodluckoreko@gmail.com, , ritaegbono@gmail.com, , hogibank@gmail.com, , markchuks55@gmail.com, , shalimatupe@gmail.com, , nuradeenyomex94@gmail.com, , emychukwuedordu@gmail.com, , abdulrahmanibrahim5145@gmail.com, , gaddafinasiru14@gmail.com, , maxonmotto@gmail.com, , ark4noah@googlemail.com, , abdullahiminuwaa@gmail.com, , enemau4real@gmail.com, , apeperita99@gmail.com, , hamzaadat@yahoo.com, , akawulawal53@gmail.com, , amintacche006@gmail.com, , abdulakeemtajudeen2@gmail.com, , robertoidama@gmail.com, , edirin4friends2@gmail.com, , lawalsalis050@gmail.com, , akposoyibo7@gmail.com, , elohoromoyibo9@gmail.com, , temistar7@gmail.com, , george_ugo77@yahoo.com, , abubakardanhajia03@gmail.com, , tasiukabir004@gmail.com, , hemmy1999@gmail.com, , rabiuibrahim473@gmail.com, , Lawalhamisu@g.com, , Perekabowei, Okubotimibi, , ibrahimmaska582@gmail.com, , edrinaawusa@gmail.com, , odibotina924@gmail.com, , noradoubra1@gmail.com, , ibrahimsaheedat2018@gmail.com, , samrichie78@gmail.com, , alexstephen2016@gmail.com, , agbaminord@gmail.com, , jiregroupofco@gmail.com, , jolly199@yahoo.co.uk, , benobu4life@gmail.com, , dorcasodumade06@gmail.com, , oyewolemuideen15@gmail.com, , omlolagold@gmail.com, , gloriaomoh88@gmail.com, , ejuomahdarlington@gmail.com, , ufuomarume@gmail.com, , olarewajutaiwo798@gmail.com, , emochovwejuliet@yahoo.com, , abdullahisalisu35otrire@gmail.com, , ajyemi300@yahoo.com, , ogelememichrist1987@mail.com, , marvelousbenji123@gmail.com, , lzzybtty@yahoo.com, , hayatbft@gmail.com, , ihiezeyiinternational@gmail.com, , abukwanzakwanza@gmail.com, , sanisalisu1989@gmail.com, , olalekanodewunmi85@gmail.com, , peterchukwuneme@gmail.com, , lawrenceanita41@gmail.com, , ireniq2@gmail.com, , Sherryfolami@gmail.com, , Olamidebabs7@gmil.com, , tajifsoft@gmail.com, , Ighoyivwifriday35@gmail.com, , omasanpatience@gmail.com, , elizabethonokpasa@yahoo.com, , samuelalika2016@gmail.com, , travelfoundation22@gmail.com, , akporhima@gmail.com, , abbey77786@gmail.com, , onafunsoventures@yahoo.com, , hamisuusman90@gmail.com, , 4zeropoint75@gmail.com, , solaoregbemi@gmail.com, , oluwafunmikeshakirat@gmail.com, , basairuabdulrazak@gmail.com, , edithgold13@gmail.com, , gborogenkate@gmail.com, , aggrehvee@gmail.com, , kehindemary@yahoo.com, , abdullsoba@gmail.com, , ifemstonny575@gmail.com, , topmayus@yahoo.com, , maryoshilim@gmail.com, , aibkmultilinks@gmail.com, , domfast2525@gmail.com, , mansurnar@gmail.com, , judecrown1991@gmail.com, , kevweoh@gmail.com, , umarahmad6425@gmail.com, , kaybex4success@gmail.com, , sdanfarnshi7@gmail.com, , ugodike75@gmail.com, , ibrahim_iaa@yahoo.com, , lovelystephen388@gmail.com, , odehdanielo@gmail.com, , wsandy400@gmail.com, , yastahglobalcompany@gmail.com, , kennyworld1234@gmail.com, , www.abduljalalbebeji2@gmail.com, , giftekemu27@gmail.com, , aseinf98@gmail.com, , onoyakporoborokpako@gmail.com, , brotherajenterprises@gmail.com, , ayoodion777@gmail.com, , bebioma@gmail.com, , obuksawas@gmail.com, , oghrince@gmail.com, , donaholubukola@gmail.com, , ochukonotoma@yahoo.com, , Elohonice@gmail.com, , lizzymax8181@gmail.com, , idiakponaflorence@gmail.com, , uniquegraphix13@gmail.com, , greatbrain4life@gmail.com, , nelsondibofu@gmail.com, , Okushimacbeth@yahoo.com, , kafayaomolade@gmail.com, , diligence4wealth@gmail.com, , julietagbure@gmail.com, , jidemogaji25@gmail.com, , rukevweoyibojoba@gmail.com, , eferakorho2016@gmail.com, , ujuolive88@gmail.com, , viviandarah4@gmail.com, , Ideh@gmail.com, , fomolade85@gmail.com, , jscobsuijah@gmail.com, , winifredakpojotor@gmail.com, , lovelye@gmail.co, , gladysosifo69@gmail.com, , egunjobitolulopeomayeli@gmail.com, , kingsversace@yahoo.com, , eravwokeefemedwin@gmail.com, , samklef4life@gmail.com, , emohefekome@gmail.com, , orhomediajacob@gmail.com, , chimafrancisca1@gmail.com, , aseinfaustina@gmail.com, , tegablessing777@gmail.com, , roselineevawere@gmail.co, , graceanuna@gmail.com, , benjaminiorkyase@gmail.com, , joebish2@gmail.com, , rukkyshawty@gmail.com, , itedjerejulius@gmail.com, , mescolnelnet68@gmail.com, , jeffkings80@gmail.com, , nelsondibofu@yahoo.com, , Nonso566@gmail.com, , kpamor5@gmail.com, , aghanaukamaka@gmail.com, , igbiri2016@gmail.com, , Orukome1976@gmail.com, , chuksudoma@gmail.com, , alvick75@gmail.com, , uchiamanasseh9@gmail.com, , evelynukpi@gmail.com, , omondarho2@gmail.com, , ezeokoyep@gmail.com, , lynxbeatentertainment@hotmail.com, , josephobiajuru@yahoo.com, , puweitamaraumiemen@gmail.com, , elijahsamson300@gmail.com, , ebitebepromise22@gmail.com, , globalstarlight16@gmail.com, , precriso@gmail.com, , peres_13@yahoo.com, , vascoliberty@gmail.com, , jessyteeonmail@gmail.com, , dinuen851@gmail.com, , obusco1982@yahoo.com, , vincentdickson14@gmail.com, , desupremenuvicare@gmail.com, , njokufrancesca@mail.com, , Chukudineku@gmail.com, , chiukpe1@gmail.com, , jenniferniovo@gmail.com, , ogboduogaga1990@gmail.com, , adewumiyetunde2017@gmail.com, , aladinsunday@gmail.com, , richardgifted445@gmail.com, , odafepeter1@gmail.com, , curvyq169@icloud.com, , andyarsekav@gmail.com, , abutugodwinichukwu@gmail.com, , tonybiu26@gmail.com, , odizuglobalresources1@gmail.com, , cathyrunor@gmail.com, , okonkwouche284@gmail.com, , vetrosun@gmail.com, , ileshasolomon1@gmail.com, , drtule@yahoo.com, , bashirabdullahihubbare27@gmail.cm, , igenisuobaid@gmail.com, , gidguy34@gmail.com, , shimagbaasylvester@gmail.com, , ajimosunayomibo@gmail.com, , idhoveefe@gmail.com, , abdullahiahmad8888@gmail.com, , doristena6@gmail.com, , hannahodunowo@gmail.com, , asuem050@gmail.com, , biniislam001@gmail.com, , ossomclifford50@gmail.com, , chiamakaodunukwe761@gmail.com, , abaguterver@gmail.com, , ovekpibeauty@gmail.com, , nanakemedaniel@gmail.com, , joachimibeh2014@gmail.com, , tyoakaasesugh@gmail.com, , alexandermichael081@gmail.com, , murtalabello461@gmail.com, , iorkyarjob@gmail.com, , sololomonomojola@yahoo.ca, , akeemumar5@gmail.com, , funmeya08@gmail.com, , olowo_adebizy@yahoo.com, , eddyrose27654@gmail.com, , paulinaceboh@gmail.com, , musaarigu@yahoo.com, , fahadsani921@gmail.com, , mubickson@gmail.com, , alomsewuese@gmail.com, , awehmail@gmail.com, , anzodorcas@gmail.com, , anassharaton@gmail.com, , lawaladeola66@gmail.com, , nazifisanyinna@gmail.com, , juliet_orighoaye@yahoo.com, , basirutbw@gmail.com, , sanihaske12@gmail.com, , eloalex7@gmail.com, , grantadugbo@gmail.com, , fridayogochukwu2018@gmail.com, , obarans@yahoo.com, , gloriaedjeba@gmail.com, , faithonomu@gmail.com, , drgbenga.ba@gmail.com, , emmaobogho@yahoo.com, , risingwada1@gmail.com, , meggieeyeta@gmail.com, , agbajordan2000@gmail.com, , iormangerjudith@gmail.com, , raymondoghenero6@gmail.com, , jeechillin27@gmail.com, , teddyvivian644@gmail.com, , peterisahdestiny@gmail.com, , bamidayo227@gmail.com, , emuoboorotoma@gmail.com, , tovia4u@gmail.com, , akundurose2019@gmail.com, , goldenjohnson59@yahoo.com, , anzoblessing@gmail.com, , charityjnr@gmail.com, , rukkynurse@gmail.com, , adamasysy100@gmail.com, , francesamaka89@gmail.com, , precibabi@gmail.com, , Oweizidepafiye@gmail.com, , johnaje.o@gmail.com, , zipporah624@gmail.com, , tunola2@gmail.com, , innocentokonye@gmail.com, , chinyereze.samuel@yahoo.com, , katsopreye@gmail.com, , kesdon9@gmail.com, , ericudutt7@gmail.com, , richpee079@gmail.com, , funmiwale99@gmail.com, , ebitony182@gmail.com, , samobi71@gmail.com, , programmermoni@gmail.com, , basharahmadbinanchi@yahoo.com, , jacksoniorfa85@gmail.com, , lameedjhamo@gmail.com, , cherishachubu@gmail.com, , adebolaoni0@gmail.com, , ogbudhurita94@gmail.com, , oyaskenneth@gmail.com, , ngukurankwahar@gmail.com, , dasdem35@gmail.com, , okwuchistella12@gmail.com, , divinemercyglobalcomputer@gmail.com, , alaowaheedcollins96@gmail.com, , sales@edgerythm.com, , bbventurespawa8@gmail.com, , gtgloconcepts@gmail.com, , OluwatosinR@gmail.com, , aikomocaroline@gmail.com, , lauwaliisiyakubaura@gmail.com, , estherakintunde01@gmail.com, , pcopara1@gmail.com, , eaniretan@gmail.com, , emekarotimi2019@gmail.com, , sayhi2gnaturevincent@gmail.com, , rainworldcommltd@gmail.com, , abuyabo2011@gmail.com, , muyideenbalogun87@gmail.com, , jowahjoe@gmail.com, , aafolabi448@gmail.com, , contentmentruth2016@gmail.com, , danny_obiora@yahoo.com, , busariadebimpe@gmail.com, , tkzanzana@gmail.com, , okoliuchennaf@gmail.com, , uchennan58@gmail.com, , gomohanny@gmail.com, , seytrom2013@yahoo.com, , mariamolasunkanmi25@gmail.com, , kenpharm45@gmail.com, , zeeikeoluwa0@gmail.com, , cedwardadebiyi@gmail.com, , frankgift922@gmail.com, , danigho56@gmail.com, , abites8@gmail.com, , solomonosekamebor@gmail.com, , rachealfunmilola2@gmail.com, , williamsonuoha5@gmail.com, , johntek77@gmail.com, , yinusanurudeenolawale@gmail.com, , kogiyouthenligtmentinitiative@gmail.com, , francisfragene@gmail.com, , taiwobolarinwa@yahoo.com, , latifatk4@gmail.com, , ikuonundus@gmail.com, , amunekeoi@gmail.com, , esthereguriase5@gmail.com, , chuks@gmail.com, , celestinec244@gmail.com, , soniae.e@gmail.com, , williamjames8252@gmail.com, , akinremibola07@gmail.com, , olabisibunmi2@gmail.com, , anitaanumudu@gmail.com, , danielbunde1998@gmail.com, , bolaosunsanmi@gmail.com, , deborahbunmi49@gmail.com, , nafdaccy@gmail.com, , omopfadekemi@gmail.com, , patriciasamuel028@gmail.com, , francisca.amuziem@yahoo.com, , edidiongudofa@gmail.com, , sabinusnwachukwu@gmail.com, , violam32@yahoo.com, , njokuikenna2015@gmail.com, , vickobaro@gmail.com, , onyinye4goodness@gmail.com, , nzeadaobi1@gmail.com, , ojostephen1968@gmail.com, , Femoenams3@gmail.com, , justicespirrow@gmail.com, , Fdomo13@gmail.com, , dayoabdulrahman3@gmail.com, , delemeshack@gmail.com, , Mosebolatan5050@gmail.com, , olaniyiajanaku@gmail.com, , jenniferochuks4@gmail.com, , emilyafoke@gmail.com, , akajagborfrank@gmail.com, , folarinoluwakemi56@gmail.com, , wurusebi@gmail.com, , daddyanita2014@gmail.com, , imonioreva@gmail.com, , owolabioluwafemi20@gmail.com, , rinsowealth@gmail.com, , arhorogheneanderson@gmail.com, , hotyusuf356@gmail.com, , patienceaamos@gmail.com, , latoyeluq1@gmail.com, , olayinkadeolu81@gmail.com, , kunleadeyinka4708@gmail.com, , edith.okpako@yahoo.com, , 1104rhythm@gmail.com, , abiolakazeem62@yahoo.com, , jaspertrent246@gmail.com, , julietwilson87@gmail.com, , janetaina0@gmail.com, , harryabrahO12@gmail.com, , ajayinifemi23@gmail.com, , dukeabam71@gmail.com, , uky2003ng@gmail.com, , annaagbusi@gmail.com, , ayodeleoshadusi@gmail.com, , blessingoroke33@gmail.com, , fooluwalogbonyinkus@gmail.com, , ogoroprosperchina@gmail.com, , lanstyolami21@gmail.com, , sunday.oyebanji@yahoo.com, , ransomeoboh@yahoo.com, , skyflex4life008@yahoo.com, , jerryjlovely@gmail.com, , lateefridwanullahi@gmail.com, , opatunjiismaheel@gmail.com, , babagonilawanliman@gmail.com, , farafara4682@gmail.com"
finalValue = emails.replace("  ", ", ")
print(finalValue)
